---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
      - id: cargo-check
