[package]
name = "hcl2"
version = "0.1.0"
authors = ["Josh Lindsey <jlindsey@remedyhealthmedia.com>"]
edition = "2018"

[dependencies.nom]
version = "5.1"
default_features = false
features = ["std"]

[dev-dependencies]
criterion = "0.3"
