[package]
name = "hcl2"
version = "0.1.0"
authors = ["Josh Lindsey <joshua.s.lindsey@gmail.com>"]
edition = "2018"

[dependencies.nom]
version = "5.1"
default_features = false
features = ["std"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parse"
harness = false
