[package]
name = "hcl2"
version = "0.1.0"
authors = ["Josh Lindsey <jlindsey@remedyhealthmedia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.nom]
version = "5.1"
default_features = false
features = ["std"]
