name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: v1-${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
      - name: Lint
        run: cargo clippy
                
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: v1-${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
      - name: Run tests
        run: cargo test --verbose
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: v1-${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
      - name: Build
        run: cargo build --verbose
